### ISSUE TITLE
Gradle Wrapper funktioniert nicht

### ISSUE THREAD

**Issue by n2o** [hhu-propra2/abschlussprojekt-so-long-and-thanks-for-all-the-fish#2]
Euer eingecheckter Gradle Wrapper funktioniert nicht. Wenn ihr das Repository clont und die Schritte aus eurer .travis.yml nachfolgt, bekommt ihr den selben Fehler wie in der CI.

Löscht mal euren eingecheckten Wrapper und installiert ihn frisch, bspw:

```
cd Artikel
rm -rf gradle gradlew gradlew.bat
gradle wrapper --gradle-version 5.2.1 --distribution-type all
./gradlew check
```

**Comment by DaveMitHut** [comment]
Danke für den Tipp! Ich habe bereits meine lokale gradle-Version geupdated, neue Wrapper generieren lassen und diese dann gepusht mit dem besprochenen force-add. Die .travis.yml führt jetzt die angegebenen Kommandos aus.

**Comment by n2o** [comment]
Noch was: du verwendest scheinbar eine Mailadresse auf deinem Rechner, die nicht mit deinem GitHub Account verknüpft ist. Daher tauchst du nicht als Contributor auf und deshalb werden deine Commits auch nicht in der Statistik mit aufgeführt
